// File generated by FlutterFire CLI.
// NOTE: You need to replace the placeholder values below with your actual Firebase project configuration.
// To get these values:
// 1. Go to Firebase Console: https://console.firebase.google.com/
// 2. Select your project (or create a new one)
// 3. Go to Project Settings > General
// 4. Scroll down to "Your apps" section
// 5. Add Android app and iOS app if not already added
// 6. Download google-services.json (Android) and GoogleService-Info.plist (iOS)
// 7. Place them in android/app/ and ios/Runner/ respectively
// 8. Run: flutterfire configure (or manually update this file)

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnQSFvxZuRrb6W03fqn4Wvgdnl7mvpYRg',
    appId: '1:180526070893:web:YOUR_WEB_APP_ID',
    messagingSenderId: '180526070893',
    projectId: 'helpnovaproject',
    authDomain: 'helpnovaproject.firebaseapp.com',
    storageBucket: 'helpnovaproject.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnQSFvxZuRrb6W03fqn4Wvgdnl7mvpYRg',
    appId: '1:180526070893:android:afef406a18d6e9816bd364',
    messagingSenderId: '180526070893',
    projectId: 'helpnovaproject',
    storageBucket: 'helpnovaproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnQSFvxZuRrb6W03fqn4Wvgdnl7mvpYRg',
    appId: '1:180526070893:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '180526070893',
    projectId: 'helpnovaproject',
    storageBucket: 'helpnovaproject.firebasestorage.app',
    iosBundleId: 'com.example.helpnovaproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnQSFvxZuRrb6W03fqn4Wvgdnl7mvpYRg',
    appId: '1:180526070893:ios:YOUR_MACOS_APP_ID',
    messagingSenderId: '180526070893',
    projectId: 'helpnovaproject',
    storageBucket: 'helpnovaproject.firebasestorage.app',
    iosBundleId: 'com.example.helpnovaproject',
  );
}
